# Dockerfile.dev

FROM debian:12.1

RUN apt-get update --quiet --yes
RUN apt-get install --quiet --yes curl
RUN apt-get install --quiet --yes ruby-full build-essential

RUN curl -fsSL https://deb.nodesource.com/setup_24.x -o node_setup.sh && \
    bash node_setup.sh && \
    apt-get install -y nodejs

RUN gem install bundler

WORKDIR /root/catsay

CMD ["sleep", "infinity"]
